Importing the libraries

In [74]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np

Importing the dataset

In [75]:
data = pd.read_csv(r'C:\Users\Mayank\Downloads\S01 - Machine-Learning-A-Z-Codes-Datasets\Machine-Learning-A-Z-Codes-Datasets\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Python\data.csv')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [76]:
x= data.iloc[: , : -1].values  # independent variable
y=data.iloc[: , -1].values # dependent variable('purchase')
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

Taking care of missing data

In [77]:
from sklearn.impute import SimpleImputer

# Create the imputer (strategy = 'mean' replaces NaN with the column mean)
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')
# Skip the first column (categorical->'Country') and apply imputation to the remaining numerical columns
x[:, 1:] = imputer.fit_transform(x[:, 1:])

In [78]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding categorical data

In [79]:
# Encoding the Independent Variable(nominal data)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Apply OneHotEncoder to the first column
# remainder='passthrough' → Keeps the remaining columns unchanged.
# ColumnTransformer → Allows you to apply transformations to specific columns.
# OneHotEncoder() → Encodes the first column as binary values.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Transform x
x = ct.fit_transform(x)

print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [80]:
# Encoding the dependent Variable(ordinal data)
from sklearn.preprocessing import LabelEncoder

# Create the LabelEncoder
le = LabelEncoder()

# Transform y
y = le.fit_transform(y)

print(y)


[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the Training set and Test set

In [81]:
from sklearn.model_selection import train_test_split

# Split the data into training and test sets (80% train, 20% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)



In [82]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [85]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [83]:
y_test

array([0, 1])

Feature Scaling

In [86]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
# Only scale columns starting from index 3 (last two numerical columns)
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

# Optional: Convert first 3 columns back to int (if needed for clarity)
x_train[:, :3] = x_train[:, :3].astype(int)
x_test[:, :3] = x_test[:, :3].astype(int)


In [87]:
x_train

array([[0, 0, 1, -0.19159184384578545, -1.0781259408412425],
       [0, 1, 0, -0.014117293757057777, -0.07013167641635372],
       [1, 0, 0, 0.566708506533324, 0.633562432710455],
       [0, 0, 1, -0.30453019390224867, -0.30786617274297867],
       [0, 0, 1, -1.9018011447007988, -1.420463615551582],
       [1, 0, 0, 1.1475343068237058, 1.232653363453549],
       [0, 1, 0, 1.4379472069688968, 1.5749910381638885],
       [1, 0, 0, -0.7401495441200351, -0.5646194287757332]], dtype=object)

In [88]:
x_test


array([[0, 1, 0, -1.4661817944830124, -0.9069571034860727],
       [1, 0, 0, -0.44973664397484414, 0.2056403393225306]], dtype=object)